export const AUDIT_ACTION_LABELS: Record<string, string> = {
  "auth.login": "Signed in",
  "auth.logout": "Signed out",
  "auth.timeout": "Signed out after inactivity",
  "auth.login_failed": "Failed sign-in",
  "auth.login_blocked": "Sign-in blocked (account disabled)",
  "user.create": "Created account",
  "user.update": "Edited account",
  "user.password_change": "Changed own password",
  "user.password_reset": "Reset password",
  "user.disable": "Disabled account",
  "user.enable": "Enabled account",
  "pr.create": "Created PR",
  "pr.update": "Edited PR details",
  "pr.move_stage": "Moved PR to another stage",
  "pr.cancel": "Cancelled PR",
  "pr.restore": "Restored PR",
};

export const AUDIT_FIELD_LABELS: Record<string, string> = {
  prNumber: "PR Number",
  prDate: "PR date",
  referenceCode: "Reference ID",
  referenceCreated: "New Reference ID created",
  prType: "Type of PR",
  prTypeId: "Type of PR (ID)",
  category: "Category",
  prCategoryId: "Category (ID)",
  endUser: "End-User",
  particulars: "Particulars",
  abc: "ABC",
  sourceOfFunds: "Source of Funds",
  procurementMode: "Procurement Mode",
  procurementModeId: "Procurement Mode (ID)",
  calendarDays: "Calendar Days",
  accountCode: "Account Code",
  receivedAt: "Received",
  stage: "Stage",
  effectiveAt: "Effective",
  movedBack: "Moved back",
  remarks: "Remarks",
  status: "Status",
  employeeId: "Employee ID",
  fullName: "Full name",
  role: "Role",
  userType: "User type",
  isActive: "Active",
  mustChangePassword: "Must change password",
  sessionsSignedOut: "Signed out everywhere",
  otherSessionsSignedOut: "Other sessions signed out",
  source: "Source",
};

export const AUDIT_AREAS = {
  auth: "Sign-ins",
  user: "Accounts",
  pr: "PRs",
} as const;

export type AuditArea = keyof typeof AUDIT_AREAS;
